# numpy 
- Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrics, along with a collection of mathematical funcitons to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [3]:
import numpy as np

##creating arrays
## create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
# reshape the array
arr2=np.array([2,3,4,5,6])
arr2.reshape((5,1))


array([[2],
       [3],
       [4],
       [5],
       [6]])

In [7]:
# nested list 
arr2=np.array([[4,5,6,7,8]])
arr2.shape

(1, 5)

In [9]:
arr2=np.array([[4,5,6,7,8],[5,3,4,4,5]])
arr2.shape

(2, 5)

In [10]:
arr2.reshape(5,2)

array([[4, 5],
       [6, 7],
       [8, 5],
       [3, 4],
       [4, 5]])

In [13]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
## identity matrix 
# all diagnals  are one 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# attributes of numpy array
arr=np.array([[1,2,3],[4,5,6]])

print('Array:\n',arr)
print('Shape:\n',arr.shape)
print('Number of dimensions:\n',arr.ndim)
print('size (no of elements):\n',arr.size)
print('Item size (in bytes):\n',arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:
 (2, 3)
Number of dimensions:
 2
size (no of elements):
 6
Item size (in bytes):
 8


In [24]:
## numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element wise addition 
print('Addition', arr1+arr2)
### Element wise subtraction 
print('Addition', arr1-arr2)
### Element wise multiplication 
print('Addition', arr1*arr2)
### Element wise division 
print('Addition', arr1/arr2)

Addition [11 22 33 44 55]
Addition [ -9 -18 -27 -36 -45]
Addition [ 10  40  90 160 250]
Addition [0.1 0.1 0.1 0.1 0.1]


In [28]:
## universal function 
arr=np.array([2,3,4,5,6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [39]:
## array slicing and indexing 

arr=np.array([[1,2,3,4,5],[5,6,7,8,9],[9,10,11,12,13]])
arr 

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 9, 10, 11, 12, 13]])

In [38]:
print(arr[0:,1])

[ 2  6 10]


In [42]:
print(arr[1:3,2:4])

[[ 7  8]
 [11 12]]


In [46]:
print(arr[0:2,2:4])


[[3 4]
 [7 8]]


In [48]:
# modify array elements
arr[0][0]=100
print(arr)

[[100   2   3   4   5]
 [  5   6   7   8   9]
 [  9  10  11  12  13]]


In [49]:
arr[1,2]=20
print(arr)

[[100   2   3   4   5]
 [  5   6  20   8   9]
 [  9  10  11  12  13]]


In [50]:
arr[1:]=50
print(arr)

[[100   2   3   4   5]
 [ 50  50  50  50  50]
 [ 50  50  50  50  50]]


In [51]:
# practical application 
# statistical concepts - Normalization 
# to have a mean of 0 amd standard deviation of 1
data=np.array([1,2,3,4,5])

mean=np.mean(data)
std_dev=np.std(data)

#normalize the data
normalized_data=(data-mean)/std_dev
print('Normalized data:',normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [57]:
# example 2 
data=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

# mean
mean=np.mean(data)
print('Mean:',mean)
# Median
median=np.median(data)
print('Median:',median)
# Standard deviation
std=np.std(data)
print('standard deviation:',std)
#varience
var=np.var(data)
print('varience',var)

Mean: 8.0
Median: 8.0
standard deviation: 4.320493798938574
standard deviation: 18.666666666666668


In [58]:
## Logical operations
data=np.array([1,2,3,4,5,6,7,9,10])
data>10

array([False, False, False, False, False, False, False, False, False])

In [64]:
data[(data>5) & (data<9)]

array([6, 7])